[package]
name = "socha"
version = "27.0.2"
license = "Apache-2.0"
description = "Offiziele Rust Bibliothek der Software Challenge Germany"
repository = "https://github.com/software-challenge/player_rust"
readme = "README.md"
keywords = ["socha", "software-challenge"]
edition = "2024"
exclude = [
    ".github/",
    "target/",
    "shell.nix",
    "connection_reads.log",
]

[dependencies]
xml = "1.4.0"

[features]
debug = ["debug-recv-comm-log"]
debug-recv-comm-log = []

[lints.clippy]
unwrap_used = "warn"
exprect_used = "warn"
indexing_slicing = "warn"
panic = "warn"